import {useCallback,useEffect,useState} from "react";
import {Activity,Archive,CheckCircle2,ChevronLeft,ChevronRight,FilePlus2,FileX2,RefreshCw,Search,UserCheck,UserX} from "lucide-react";
import {Area,AreaChart,Bar,BarChart,CartesianGrid,Cell,Legend,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from "recharts";
import API from "../services/api";
import {useToast} from "../components/ToastProvider";
import {apiMessage} from "../utils/errors";
import {relativeTime} from "../utils/relativeTime";

const COLORS=["#8b5cf6","#10b981","#f59e0b"];const roleColors=["#4f46e5","#06b6d4"];
const filters=[['','All actions'],['created','Created'],['updated','Updated'],['published','Published'],['deleted','Deleted'],['archived','Archived'],['user_activated','User Activated'],['user_deactivated','User Deactivated']];
function activityMeta(action=""){if(action.includes("deactivated"))return {Icon:UserX,label:"User Deactivated",tone:"orange"};if(action.includes("activated"))return {Icon:UserCheck,label:"User Activated",tone:"green"};if(action.includes("publish"))return {Icon:CheckCircle2,label:"Published",tone:"purple"};if(action.includes("delete"))return {Icon:FileX2,label:"Deleted",tone:"red"};if(action.includes("archive"))return {Icon:Archive,label:"Archived",tone:"gray"};if(action.includes("update"))return {Icon:RefreshCw,label:"Updated",tone:"blue"};if(action.includes("creat"))return {Icon:FilePlus2,label:"Created",tone:"green"};return {Icon:Activity,label:"Activity",tone:"gray"}}
function ChartCard({title,subtitle,children}){return <section className="admin-panel chart-card"><div className="panel-heading"><div><h2>{title}</h2><p>{subtitle}</p></div></div><div className="chart-wrap">{children}</div></section>}

export default function AdminAnalytics(){
  const [data,setData]=useState(null);const [activity,setActivity]=useState({items:[],total:0});const [page,setPage]=useState(1);const [activityLoading,setActivityLoading]=useState(true);const [controls,setControls]=useState({search:"",action:"",sort:"desc"});const toast=useToast();
  useEffect(()=>{API.get("/dashboard/admin").then(r=>setData(r.data)).catch(e=>toast.error(apiMessage(e,"Unable to load analytics")))},[toast]);
  const loadActivity=useCallback(()=>{setActivityLoading(true);API.get("/admin/activity",{params:{page,page_size:25,search:controls.search||undefined,action:controls.action||undefined,sort:controls.sort}}).then(r=>setActivity(r.data)).catch(e=>toast.error(apiMessage(e,"Unable to load activity"))).finally(()=>setActivityLoading(false))},[controls,page,toast]);
  useEffect(()=>{const timer=setTimeout(loadActivity,200);return()=>clearTimeout(timer)},[loadActivity]);
  useEffect(()=>{if(data&&window.location.hash==="#activity")setTimeout(()=>document.getElementById("activity")?.scrollIntoView({behavior:"smooth"}),100)},[data]);
  const update=(key,value)=>{setPage(1);setControls(current=>({...current,[key]:value}))};const pages=Math.max(1,Math.ceil(activity.total/25));
  if(!data)return <main className="page-shell admin-page"><div className="skeleton chart-skeleton"/></main>;
  return <main className="page-shell admin-page"><header className="admin-page-header"><div><span className="eyebrow">Platform intelligence</span><h1>Analytics</h1><p>Understand what happened over time and investigate platform activity.</p></div></header>
    <section className="analytics-grid"><ChartCard title="Forms by Status" subtitle="Current lifecycle distribution"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={data.forms_by_status} dataKey="value" nameKey="name" innerRadius={62} outerRadius={92} paddingAngle={4}>{data.forms_by_status.map((_,i)=><Cell key={i} fill={COLORS[i]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></ChartCard><ChartCard title="Users by Role" subtitle="Access-level distribution"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.users_by_role} layout="vertical" margin={{left:16}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" allowDecimals={false}/><YAxis dataKey="name" type="category" width={88}/><Tooltip/><Bar dataKey="value" radius={[0,8,8,0]}>{data.users_by_role.map((_,i)=><Cell key={i} fill={roleColors[i]}/>)}</Bar></BarChart></ResponsiveContainer></ChartCard><ChartCard title="Responses Over Time" subtitle="Submission volume over the last 14 days"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.responses_over_time}><defs><linearGradient id="responseGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#635bff" stopOpacity={.35}/><stop offset="95%" stopColor="#635bff" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Area type="monotone" dataKey="responses" stroke="#635bff" strokeWidth={3} fill="url(#responseGradient)"/></AreaChart></ResponsiveContainer></ChartCard><ChartCard title="Forms Created Over Time" subtitle="New forms over the last 14 days"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.forms_over_time}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="date" tick={{fontSize:11}}/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="forms" fill="#06b6d4" radius={[7,7,0,0]}/></BarChart></ResponsiveContainer></ChartCard></section>
    <section className="analytics-activity-section" id="activity"><div className="activity-section-header"><div><span className="eyebrow">Operational history</span><h2>Recent Activity Timeline</h2><p>Search and investigate the complete audit trail.</p></div><span className="count-pill">{activity.total} events</span></div>
      <div className="activity-controls"><label className="activity-search"><Search/><input value={controls.search} onChange={e=>update("search",e.target.value)} placeholder="Search action, form ID, user, or entity…" aria-label="Search activity"/></label><select value={controls.action} onChange={e=>update("action",e.target.value)} aria-label="Filter activity type">{filters.map(([value,label])=><option value={value} key={value}>{label}</option>)}</select><select value={controls.sort} onChange={e=>update("sort",e.target.value)} aria-label="Sort activity"><option value="desc">Newest first</option><option value="asc">Oldest first</option></select></div>
      <div className="activity-log-card">{activityLoading?[1,2,3,4,5].map(i=><div className="skeleton activity-row-skeleton" key={i}/>):activity.items.length?activity.items.map(item=>{const {Icon,label,tone}=activityMeta(item.action);const exact=new Date(item.created_at).toLocaleString();return <article className="activity-log-row" key={item.id}><span className={`activity-type-icon ${tone}`}><Icon/></span><div className="activity-log-copy"><div><strong>{item.action.replaceAll("."," ")}</strong><span className={`activity-type-badge ${tone}`}>{label}</span></div><p>By {item.user_name} · {item.entity_type}{item.entity_id?` #${item.entity_id}`:""}</p></div><div className="activity-time"><time title={exact}>{relativeTime(item.created_at)}</time><small>{exact}</small></div></article>}):<div className="dashboard-empty"><Activity/><h2>No activity found</h2><p>Try a different search or filter.</p></div>}</div>
      {activity.total>25&&<nav className="activity-pagination" aria-label="Activity pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft/> Previous</button><span>Page {page} of {pages}</span><button disabled={page===pages} onClick={()=>setPage(p=>p+1)}>Next <ChevronRight/></button></nav>}
    </section>
  </main>
}
