import {useCallback,useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {AlertTriangle,ArrowRight,CheckCircle2,Database,Download,FileClock,FileText,LayoutDashboard,Server,ShieldCheck,Sparkles,TrendingUp,UserX,Users,Wifi} from "lucide-react";
import {useAuth} from "../auth/AuthContext";
import API from "../services/api";
import {useToast} from "../components/ToastProvider";
import {apiMessage} from "../utils/errors";
import {relativeTime} from "../utils/relativeTime";

const compact=new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:1});
function MetricCard({label,value,note,growth,progress,tone,icon:Icon}){return <article className={`dashboard-kpi ${tone}`}><div className="dashboard-kpi-top"><span className="dashboard-kpi-icon"><Icon/></span><span className="dashboard-growth"><TrendingUp/> {growth}</span></div><strong>{compact.format(value||0)}</strong><h2>{label}</h2><p>{note}</p><div className="dashboard-progress"><i style={{width:`${Math.max(8,Math.min(progress||0,100))}%`}}/></div></article>}

export default function AdminDashboard(){
  const [data,setData]=useState(null);const [loading,setLoading]=useState(true);const toast=useToast();const {user}=useAuth();
  const load=useCallback((silent=false)=>API.get("/dashboard/admin").then(r=>setData(r.data)).catch(e=>{if(!silent)toast.error(apiMessage(e,"Unable to load admin dashboard"))}).finally(()=>setLoading(false)),[toast]);
  useEffect(()=>{load();const timer=setInterval(()=>load(true),60000);return()=>clearInterval(timer)},[load]);
  const exportReport=()=>{if(!data)return;const rows=[["Metric","Value"],["Total Users",data.total_users],["Active Users",data.active_users],["Total Forms",data.total_forms],["Published Forms",data.published_forms],["Draft Forms",data.draft_forms],["Archived Forms",data.archived_forms],["Total Responses",data.response_count]];const blob=new Blob([rows.map(row=>row.join(",")).join("\n")],{type:"text/csv"});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=`formflow-report-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url)};
  if(loading)return <main className="page-shell admin-page dashboard-page"><div className="skeleton dashboard-hero-skeleton"/><div className="dashboard-kpi-grid">{[1,2,3,4].map(i=><div className="skeleton card" key={i}/>)}</div></main>;
  if(!data)return null;
  const maxTotal=Math.max(data.total_users,data.total_forms,data.response_count,1);const status=data.platform_status;const attention=data.needs_attention;
  const kpis=[{label:"Total Users",value:data.total_users,note:"Registered platform accounts",growth:`+${data.users_this_week} this week`,progress:data.total_users/maxTotal*100,tone:"violet",icon:Users},{label:"Total Forms",value:data.total_forms,note:"Forms across all workspaces",growth:`+${data.forms_this_week} this week`,progress:data.total_forms/maxTotal*100,tone:"blue",icon:FileText},{label:"Published Forms",value:data.published_forms,note:"Live and collecting responses",growth:`${data.total_forms?Math.round(data.published_forms/data.total_forms*100):0}% live`,progress:data.total_forms?data.published_forms/data.total_forms*100:0,tone:"green",icon:CheckCircle2},{label:"Total Responses",value:data.response_count,note:"Submissions collected to date",growth:`+${data.responses_this_week} this week`,progress:data.response_count/maxTotal*100,tone:"amber",icon:TrendingUp}];
  return <main className="page-shell admin-page dashboard-page">
    <header className="dashboard-hero"><div className="dashboard-hero-copy"><span className="dashboard-overline"><Sparkles/> Operations center</span><h1>Welcome back, {user?.name||"Platform Owner"}</h1><p>Monitor platform health, spot items that need attention, and keep daily operations moving.</p></div><div className="dashboard-hero-meta"><time>{new Date().toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric",year:"numeric"})}</time><span className="dashboard-live"><i/> All systems live</span></div></header>
    <section className="dashboard-kpi-grid">{kpis.map(item=><MetricCard {...item} key={item.label}/>)}</section>
    <section className="operations-grid">
      <article className="operations-card status-card"><div className="dashboard-card-heading"><div><h2>Live platform status</h2><p>Current service availability</p></div><Wifi/></div><div className="status-monitor"><div><span><Server/></span><p><strong>Backend Status</strong><small>{status.backend}</small></p><i/></div><div><span><Database/></span><p><strong>Database Status</strong><small>{status.database}</small></p><i/></div><div><span><ShieldCheck/></span><p><strong>API Status</strong><small>{status.api}</small></p><i/></div><div><span><Users/></span><p><strong>Active Users</strong><small>{status.active_users} accounts</small></p><b>{status.active_users}</b></div><div><span><CheckCircle2/></span><p><strong>Active Forms</strong><small>Published forms</small></p><b>{status.active_forms}</b></div></div></article>
      <article className="operations-card attention-card"><div className="dashboard-card-heading"><div><h2>Needs attention</h2><p>Items worth reviewing now</p></div><AlertTriangle/></div><div className="attention-list"><Link to="/admin/forms"><span className="amber"><FileClock/></span><p><strong>Old draft forms</strong><small>Not updated in 7+ days</small></p><b>{attention.stale_drafts}</b></Link><Link to="/admin/forms"><span className="red"><AlertTriangle/></span><p><strong>Flagged forms</strong><small>Awaiting moderation</small></p><b>{attention.flagged_forms}</b></Link><Link to="/admin/users"><span className="gray"><UserX/></span><p><strong>Deactivated users</strong><small>Accounts without access</small></p><b>{attention.deactivated_users}</b></Link><Link to="/admin/forms"><span className="blue"><FileText/></span><p><strong>Forms with no responses</strong><small>May need follow-up</small></p><b>{attention.forms_without_responses}</b></Link></div></article>
    </section>
    <section className="dashboard-management-card quick-management-wide"><div className="dashboard-card-heading"><div><h2>Quick management</h2><p>Common operational tasks</p></div><ShieldCheck/></div><div className="dashboard-actions"><Link to="/admin/users"><span className="action-icon violet"><Users/></span><div><strong>Manage Users</strong><small>Access and account status</small></div><ArrowRight/></Link><Link to="/admin/forms"><span className="action-icon blue"><FileText/></span><div><strong>Review Forms</strong><small>Moderation and oversight</small></div><ArrowRight/></Link><Link to="/admin/analytics"><span className="action-icon green"><LayoutDashboard/></span><div><strong>View Analytics</strong><small>Explore trends and activity history</small></div><ArrowRight/></Link><button onClick={exportReport}><span className="action-icon amber"><Download/></span><div><strong>Export Reports</strong><small>Download a CSV summary</small></div><ArrowRight/></button></div></section>
    <section className="people-grid"><article className="operations-card"><div className="dashboard-card-heading"><div><h2>Top creators</h2><p>Most active users by forms and responses</p></div><TrendingUp/></div><div className="people-list">{data.top_creators.map((creator,index)=><div key={creator.id}><span>{index+1}</span><i>{creator.name.slice(0,2).toUpperCase()}</i><p><strong>{creator.name}</strong><small>{creator.email}</small></p><b>{creator.forms_count} forms · {creator.responses_count} responses</b></div>)}</div></article><article className="operations-card"><div className="dashboard-card-heading"><div><h2>Recent registrations</h2><p>Newest accounts on the platform</p></div><Users/></div><div className="people-list">{data.recent_registrations.map(person=><div key={person.id}><i>{person.name.slice(0,2).toUpperCase()}</i><p><strong>{person.name}</strong><small>{person.email}</small></p><b title={new Date(person.created_at).toLocaleString()}>{relativeTime(person.created_at)}</b></div>)}</div></article></section>
  </main>
}
